### PR TITLE
Fixing the volume slider for mp3-streams

### PR DESCRIPTION
**Pull request by wrngwrld**

### CODE REVIEW

**Comment by jacklandrin** [comment]
I just merged the last pr. 
```
sliderVolume = UserDefaults.standard.value(forKey: volumeKey) as! Float
```
it crashed at the first running. 

Suggest use the safer way to convert type, like
 ```
 if let newValue = UserDefaults.standard.value(forKey: volumeKey) as? Float
{

}
```

You can add some protects, and make new pull request.

**Comment by jacklandrin** [comment]
Besides, there is a new language localizable.string today, Turkish.

**Comment by wrngwrld** [comment]
Sorry for the inconvenience.

I hope the changes fixes the problems!

**Comment by jacklandrin** [comment]
> Sorry for the inconvenience.
> 
> I hope the changes fixes the problems!

Never mind. I tested it. I can normally run. The feature will publish in the version 2.1. Thank you for the contribution.

**Pull request merged**
