### PR TITLE
App icon proposal

### PR DESCRIPTION
**Pull request by Zabriskije**
I've come up with a new idea for the app icon. If you mind losing the original one with this pull request, [here's a ZIP](https://github.com/jacklandrin/OnlySwitch/files/13400180/OnlySwitch-App-Icon.zip) with all the new assets (PNG + ICNS + Iconset).

### CODE REVIEW

**Comment by jacklandrin** [comment]
Hi @Zabriskije,
I appreciate your fantastic work. The app icon is exquisite with a neomorphic style. To be honest, I love your design.
I always consider exchanging a new icon for OnlySwitch, but I don't have good design skills. Though my current icon does look not good, I believe that it already built certain users' cognition. Thus, I expect there are some connections between old and new designs, which help easily transition to new visual cognition. I don't expect to see a situation where users say where OnlySwitch is when they update to the new icon. 
So, shall we find a compromise plan? To have a better design and keep the users' visual cognition for OnlySwitch.
Thank you again!

**Comment by Zabriskije** [comment]
Thanks for the compliments <3

The one below was my first design, and the one that most resembles the current icon:



I've tried first using the current gradient but it limited the slider's internal colors, so I opted for a dark blue instead.

Although I understand the icon recognition issue, I think we can get away with the pull request icon since the app is used via the menu bar, doesn't get closed, and launches itself at startup. If the normal user path for using the app would be via Launcher or the Apps folder I could see this as a more substantial issue – but that's obviously up to you :)

**Comment by jacklandrin** [comment]
Thanks for the reply!
From a regular usage perspective, maybe you are right. But I also consider other things such as promotion.
The first design looks like OneSwitch's icon. I think the name OnlySwitch already made many users confused. Basically, I like your white blue design. The current purple blue gradient was inspired by the theme color of Big Sur, but it has been out of date. My idea is that we can keep the two toggles design with neomorphic style and use white blue as the theme color. It would be better. Do you think so?
Actually, I am considering changing the separating icon( ·|· ) on the menu bar as well. If you have a good idea, feel free to share it to me. 
Thank you

**Comment by Zabriskije** [comment]
Something like this?

 

For the separating icon: I like minimal stuff, so I would go for a small filled circle when items are hidden and an outlined one when shown ● ○

**Comment by jacklandrin** [comment]
> Something like this?
> 
>  
> 
> For the separating icon: I like minimal stuff, so I would go for a small filled circle when items are hidden and an outlined one when shown ● ○

Nice job, man! I prefer the first design. If the toggles can have the outer shadow as same as the second one, I think it would be better. But it's up to you, you already finished the elegant work. Please update the pull request if could.
Regarding the separating icon, I think your idea is good. I will try to update it in the next version.
I know sometimes the iterative discussions about design are annoying and your initial pull request is indeed awesome, but as a product, I have to consider kinds of factors. Thank you so much again for your contribution.

**Comment by Zabriskije** [comment]
Hot take: iterative design discussions = bug fixes 🤓
I'm always happy to receive feedback, and you made a valid point, so it's all good.

Again, thanks for the kind words, and let me know if you're happy with the result.

**Review by jacklandrin — APPROVED** [review]
approve

**Pull request merged**
